name: app
type: 'python:3.11'

web:
  commands:
    start: gunicorn wsgi:app --bind 0.0.0.0:${PORT:-8000}
  locations:
    "/":
      root: ""    # empty string means project root directory

dependencies:
  python3:
    pipenv: "2022.12.19"
