name: app
type: "python:3.13"

dependencies:
  python3:
    pipenv: "2022.12.19"

hooks:
  build: |
    set -eu
    pipenv install --deploy --system

web:
  commands:
    start: gunicorn wsgi:app
  locations:
    "/":
      root: ""
      passthru: false
