name: app
type: "python:3.10"

dependencies:
  python3:
    pipenv: "2022.12.19"

hooks:
  build: |
    set -eu
    pipenv install --system --deploy

web:
  commands:
    start: gunicorn wsgi:application
  locations:
    "/":
      root: ""
      passthru: false
