name: app
type: "python:3.10"

dependencies:
    python:
        flask: "*"
        gunicorn: "*"

web:
    commands:
        start: gunicorn wsgi:application
    locations:
        "/":
            root: ""
            passthru: false

mounts: {}
relationships: {}
