name: app

type: "python:3.9"

dependencies:
  python:
    pip: "23.2.1"

hooks:
  build: |
    pip install -r requirements.txt

web:
  commands:
    start: python app.py
  locations:
    "/":
      root: ""
      passthru: false
      allow: true

mounts:
  "/data": "shared:data"

disk: 256
