name: app
type: "python:3.10"

build:
    flavor: none

build_hook: |
    pip install -r requirements.txt

web:
    commands:
        start: gunicorn wsgi:application
    locations:
        "/":
            root: ""
            passthru: false

mounts: {}
relationships: {}
